class Textos {
  static const String textoHomePage =
      "Estudante de graduação no Instituo Mauá de Tecnologia no curso de Ciência da Computação com previsão de formação em dez/2027. Interesse profissional em Full Stack e Inteligência Artificial.";
  static const String textoPython =
      "O Python foi a primeira linguagem que aprendi. Meu primeiro contato foi em uma disciplina eletiva básica no Ensino Médio chamada 'Programe para não ser programado'. Entre o Ensino Médio e o Superior fiz um curso completo na Hashtag Treinamentos, onde aprendi o básico da linguagem, algumas bibliotecas, orientação a objetos e conteúdos mais avançados. Já na faculdade, as ferramentas essenciais do Python foram ensinadas na disciplina 'Lógica da Progrmação', no primeiro semestre, enquanto na matéria 'Estatística', no segundo semeste, foram ensinadas bibliotecas como SciPy, Pandas, MatPlotLib e outras. Python é a linguagem de programação que possuo maior entendimento e é minha favorita!";
  static const String textoJava =
      "Fui apresentado à linguagem Java no primeiro semestre da faculdade e já foi extremamente importante. A disciplina responsável por ensinar Java foi a 'Programação Orientada a Objetos' e me apresentou pela primeira vez o que realmente é este estilo de programação e sua importância. Meu primeiro grande projeto de software foi escrito em Java, onde eu e meu grupo fizemos um jogo de perguntas e respostas sobre linguagens de programação. Ao longo da disciplina e do projeto, além da própria linguagem, aprendi sua integração com bancos de dados e bibliotecas gráficas, como JavaFX e JavaSwing. Fiz um curso de programação orientada à onjetos da Oracle juntamente da disciplina citada. Gosto muito de programar em Java e tenho interesse em me aprofundar mais!";
  static const String textoFlutter =
      "A primeira vez que ouvi falar em Flutter foi no Projeto e Atividade Especial (PAE) que realizaei no segundo semestre do meu curso da Mauá, chamado 'Desenvolvimento de Aplicações Híbridas com Flutter'. Pensei em estudar um pouco mais sobre desenvolvimento Front End, já que apenas tinha tido contato com Back End em Java e Python. Logo percebi que o Flutter se trata de uma ferramenta muito poderosa que integra o Front e Back End de maneira simples, possibilitando o desenvolvedor a criar projetos muito completos, como este site (espero que esteja completo!). O Framework despertou meu interesse pela área e se tornou uma das minhas ferramentas de código prediletas.";
  static const String textoBD =
      "O SQL me foi apresentado no primeiro semestre da faculdade, na disciplina 'Banco de Dados Relacionais'. A matéria foi muito interessante e realmente entendi o que é um banco de dados, despertando meu interesse por eles. Aprendendo MySQL pude entender a importância deles e que estão presentes em praticamente todas as aplicações profissionais. O primeiro grande projeto de software que fiz, um jogo de perguntas e respostas, a integração do Java e MySQL foi mais do que necessária para a realização de um jogo bem desenvolvido. Tenho algum conhecimento de MongoDB também e estou disposto a aprender mais sobre os bancos de dados no geral.";
  static const String textoHtml =
      "Html foi meu primeiro contato com o desenvolvimento Front End. Na disciplina de 'Desenvolvimento Front End', no segundo semestre da Mauá, aprendi os conceitos básicos da linguagem, juntamente do básico de CSS. Além disso, nos foi apresentado Framework Bootstrap, e pude entender como essas ferramentas podem ser poderosas quando usadas em conjunto. Também no segundo semestre da faculdade fiz a área de 'Doe Já' para o site da APAE-SCS, integrando Html, CSS e Bootstrap com o Javascrpit e MySQL, sendo assim meu primeiro projeto Full Stack.";
  static const String textoJavaScript =
      "O JavaScript foi ensinado no segundo semestre do meu curso de graduação na Mauá, na disciplina 'Desenvolvimento Front end'. A linguagem foi apresentada como uma das melhores alternativas de integrar o Front End de um projeto escrito em Html e CSS ao Back End. Em um projeto realizado também no segundo semestre, fiz exatamente essa integração para desenvolver a área de 'Doe Já' para o site da APAE-SCS.";
  static const String textoGit =
      "O Git é uma ferramenta essencial para todos os desenvolvedores hoje em dia e não posso deixar de adicionar aos meus conhecimentos. Ao longo do meu curso de graduação na Mauá percebi sua importância e a facilidade que ele fornece ao desenvolver projetos em grupos. Além disso o GitHub é uma ferramenta muito boa para desnvolvedores encontrarem projetos similares, tirarem dúvidas e publicarem seus projetos pessoais.";
  static const String textoArduino =
      "A eletrônica é um interesse que sempre tive, e o uso de componentes eletrônicos programados em computador para funcionar da maneira desejada para criar dispositivos inteligentes é a união de dois interesses, o software e a eletrônica. Meu primeiro contato com o Arduino foi em um kit que ganhei que possuia um curso integrado à ele. Após isso, no primeiro semestre da graduação na Mauá fiz um Projeto e Atividade Especial (PAE) chamado 'Internet das Coisas e Conectividade - Do Arduino ao ESP32 com WiFi, Bluetooth e LoRa', onde tive maior contato com as funcionalidades da ferramenta.";
  static const String textoIngles =
      "O inglês é imprescindível para o desenvolvimento de um bom profissional na maioria das áreas hoje em dia, e na Ciência da Computação essa importância se faz cada vez mais presente. Desde os 5 anos de idade comecei minhas aulas de inglês na escola Red Balloon, onde me formei em 2019. Tenho grande familiaridade com a língua e me considero fluente nela.";
  static const String textoEspanhol =
      "O espanhol é uma das línguas mais faladas no mundo e importante para se comunicar com muitas nacionalidades diferentes. Por conta de minha ascendência espanhola sempre tive contato com a língua e me formei em um curso de verão no Colegio de España, em Salamanca. Me considero quase fluente na língua, já que consigo me comunicar e entender o espanhol facilmente, mas não estudei a língua o suficiente para saber conjugar perfeitamente os verbos, e meu vocabulário ainda é um pouco escasso.";
  static const String descCodeQuests =
      "Jogo de perguntas e respostas sobre Java, Python e SQL. Feito como Projeto Integrador do primeiro semestre";
  static const String descAPAE =
      "Área de 'Doe Já' do site da APAE-SCS. Feito como Projeto Integrador do segundo semestre";
  static const String descPortfolio = "Este site que você está vendo! Feito como projeto final da PAE de Flutter";
}
